### ISSUE TITLE
Running autoedit.py results in error

### ISSUE THREAD

**Issue by KnoBuddy** [LAION-AI/ldm-finetune#6]
`python autoedit.py --edit test.png --model_path inpaint.pt`

```
Traceback (most recent call last):
  File "C:\Users\paperspace\anaconda3\envs\ldm\ldm-finetune\autoedit.py", line 498, in <module>
    args = parse_args()
  File "C:\Users\paperspace\anaconda3\envs\ldm\ldm-finetune\autoedit.py", line 471, in parse_args
    parser.add_argument(
  File "C:\Users\paperspace\anaconda3\envs\ldm\lib\argparse.py", line 1422, in add_argument
    action = action_class(**kwargs)
TypeError: _StoreTrueAction.__init__() got an unexpected keyword argument 'type'
```

**Comment by KnoBuddy** [comment]
Fixed the issue by changing line474 of autoedit.py.

`action=store_true`

to

`default="True"`

I'll see if I can make a PR when I get home later today.

**Comment by KnoBuddy** [comment]
New error after fixing the lines above:

```
Traceback (most recent call last):
  File "C:\Users\paperspace\anaconda3\envs\ldm\ldm-finetune\autoedit.py", line 498, in <module>
    args = parse_args()
  File "C:\Users\paperspace\anaconda3\envs\ldm\ldm-finetune\autoedit.py", line 471, in parse_args
    parser.add_argument(
  File "C:\Users\paperspace\anaconda3\envs\ldm\lib\argparse.py", line 1422, in add_argument
    action = action_class(**kwargs)
TypeError: _StoreTrueAction.__init__() got an unexpected keyword argument 'type'
```

**Comment by KnoBuddy** [comment]
Okay, I rebuilt the repo with the autoedit branch and after trial and error with different python versions, 3.8 seems to work but I ran out of GPU and didn't have time to tweak the prompt to see if I could make it run with the limited 16gb I was working with.

Either way I'm closing this.

**Comment by KnoBuddy** [comment]
This is for the AutoEdit branch.

Autoedit itself runs fine without input however if I give it an input image of 256x256 in either png or npy format it spits out the following error:

```
Traceback (most recent call last):
  File "autoedit.py", line 422, in <module>
    main(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "autoedit.py", line 182, in main
    device=device,
  File "/content/ldm-finetune/guided_diffusion/predict_util.py", line 183, in load_diffusion_model
    model, diffusion = create_model_and_diffusion(**model_config)
  File "/content/ldm-finetune/guided_diffusion/script_util.py", line 137, in create_model_and_diffusion
    timestep_respacing=timestep_respacing,
  File "/content/ldm-finetune/guided_diffusion/script_util.py", line 450, in create_gaussian_diffusion
    rescale_timesteps=rescale_timesteps,
  File "/content/ldm-finetune/guided_diffusion/respace.py", line 86, in __init__
    super().__init__(**kwargs)
  File "/content/ldm-finetune/guided_diffusion/gaussian_diffusion.py", line 148, in __init__
    assert self.alphas_cumprod_prev.shape == (self.num_timesteps,)
AssertionError
```

I have tried using various models and settings with no success.

**Comment by KnoBuddy** [comment]
Running the script by itself works fine but with the setting --edit and a PNG file I get the following error:

```Traceback (most recent call last):
  File "autoedit.py", line 416, in <module>
    main(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "autoedit.py", line 182, in main
    device=device,
  File "/content/drive/MyDrive/autoedit/ldm-finetune/guided_diffusion/predict_util.py", line 183, in load_diffusion_model
    model, diffusion = create_model_and_diffusion(**model_config)
  File "/content/drive/MyDrive/autoedit/ldm-finetune/guided_diffusion/script_util.py", line 137, in create_model_and_diffusion
    timestep_respacing=timestep_respacing,
  File "/content/drive/MyDrive/autoedit/ldm-finetune/guided_diffusion/script_util.py", line 450, in create_gaussian_diffusion
    rescale_timesteps=rescale_timesteps,
  File "/content/drive/MyDrive/autoedit/ldm-finetune/guided_diffusion/respace.py", line 86, in __init__
    super().__init__(**kwargs)
  File "/content/drive/MyDrive/autoedit/ldm-finetune/guided_diffusion/gaussian_diffusion.py", line 148, in __init__
    assert self.alphas_cumprod_prev.shape == (self.num_timesteps,)
AssertionError```
